/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.MySQL;

/**
 *
 * @author mohan
 */
public class Add_Bill_Prices extends javax.swing.JPanel {

    /**
     * Creates new form Add_Bill_Prices
     */
    int Bill_Id = 0;

    public Add_Bill_Prices(int billId) {
        initComponents();
        this.Bill_Id = billId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ecg = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        general = new javax.swing.JCheckBox();
        dental = new javax.swing.JCheckBox();
        metabolic = new javax.swing.JCheckBox();
        xray = new javax.swing.JCheckBox();
        mri = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        physiotherapy = new javax.swing.JCheckBox();
        vaccin = new javax.swing.JCheckBox();
        surgery = new javax.swing.JCheckBox();
        ultrasound = new javax.swing.JCheckBox();

        ecg.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ecg.setText("ECG");

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Treatment Prices to Bill");

        general.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        general.setText("General");
        general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalActionPerformed(evt);
            }
        });

        dental.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dental.setText("Dental Check-up");
        dental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dentalActionPerformed(evt);
            }
        });

        metabolic.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        metabolic.setText("Basic Metabolic Panel");
        metabolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metabolicActionPerformed(evt);
            }
        });

        xray.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        xray.setText("X-Ray");

        mri.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        mri.setText("MRI Scan");
        mri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mriActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 150, 136));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add to Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        physiotherapy.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        physiotherapy.setText("Physiotherapy Session");
        physiotherapy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physiotherapyActionPerformed(evt);
            }
        });

        vaccin.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        vaccin.setText("Vaccination (Flu Shot)");
        vaccin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinActionPerformed(evt);
            }
        });

        surgery.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        surgery.setText("Minor Surgery (Suturing)");
        surgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryActionPerformed(evt);
            }
        });

        ultrasound.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ultrasound.setText("Ultrasound (Abdominal)");
        ultrasound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultrasoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(general, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dental, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metabolic, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xray, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ecg, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mri, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(physiotherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccin, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surgery, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ultrasound, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(general)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ecg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metabolic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xray)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(physiotherapy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vaccin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surgery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultrasound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            if (Bill_Id != 0) {

                StringBuilder insertQuery = new StringBuilder();
                insertQuery.append("INSERT INTO bills_has_treatment_prices (bills_bill_id, treatment_prices_id) VALUES ");

                List<String> values = new ArrayList<>();
                double price = 0;
                if (general.isSelected()) {
                    values.add("('" + Bill_Id + "',1 )");
                    price = price + 2500;
                }
                if (ecg.isSelected()) {
                    values.add("('" + Bill_Id + "',3 )");
                    price = price + 1800;
                }
                if (metabolic.isSelected()) {
                    values.add("('" + Bill_Id + "',4 )");
                    price = price + 3000;
                }
                if (dental.isSelected()) {
                    values.add("('" + Bill_Id + "',2)");
                    price = price + 1200;
                }
                if (xray.isSelected()) {
                    values.add("('" + Bill_Id + "',5)");
                    price = price + 4500;
                }
                if (mri.isSelected()) {
                    values.add("('" + Bill_Id + "', 6)");
                    price = price + 12000;
                }
                if (physiotherapy.isSelected()) {
                    values.add("('" + Bill_Id + "', 7)");
                    price = price + 2000;
                }
                if (vaccin.isSelected()) {
                    values.add("('" + Bill_Id + "', 8)");
                    price = price + 1500;
                }
                if (surgery.isSelected()) {
                    values.add("('" + Bill_Id + "', 9)");
                    price = price + 6000;
                }
                if (ultrasound.isSelected()) {
                    values.add("('" + Bill_Id + "', 10)");
                    price = price + 5500;
                }

                // Only execute insert if at least one permission is selected
                if (!values.isEmpty()) {
                    insertQuery.append(String.join(", ", values));
                    MySQL.execute(insertQuery.toString());

                    JOptionPane.showMessageDialog(this, "Add Treatment Prices to Bill successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    try {
                        MySQL.execute("UPDATE `bills` SET `total_amount`='" + price + "' WHERE `bill_id`='" + Bill_Id + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Treatment Prices selected. Please Select Treatment.", "Info", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please Select ", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalActionPerformed

    private void dentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dentalActionPerformed

    private void metabolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metabolicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metabolicActionPerformed

    private void mriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mriActionPerformed

    private void physiotherapyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physiotherapyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physiotherapyActionPerformed

    private void vaccinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinActionPerformed

    private void surgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surgeryActionPerformed

    private void ultrasoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultrasoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultrasoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dental;
    private javax.swing.JCheckBox ecg;
    private javax.swing.JCheckBox general;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox metabolic;
    private javax.swing.JCheckBox mri;
    private javax.swing.JCheckBox physiotherapy;
    private javax.swing.JCheckBox surgery;
    private javax.swing.JCheckBox ultrasound;
    private javax.swing.JCheckBox vaccin;
    private javax.swing.JCheckBox xray;
    // End of variables declaration//GEN-END:variables
}
